[package]
name = "hexis-gossip"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2.6.0"
solana-sdk = "1.18.26"
lru = "0.12.5"
serde = "1.0.210"
bincode = "1.3.3"

[[bin]]
name = "hexis-gossip"
path = "src/main.rs"
